language: python
python:
- '3.5'
- '3.6'
- '3.7'
- '3.8'
install:
- pip install coverage coveralls
- python bootstrap.py
- "./bin/buildout"
script:
- coverage erase
- coverage run ./bin/test
- coveralls
deploy:
  provider: pypi
  on:
    tags: true
  user: __token__
  password: pypi-AgEIcHlwaS5vcmcCJDk3Yjc3YmZkLWNiYzEtNDdiYy04N2NhLTIwODdhMGQwOThhYgACJXsicGVybWlzc2lvbnMiOiAidXNlciIsICJ2ZXJzaW9uIjogMX0AAAYguA1UjBDYvmLIFfcQSzKd5HSrNuyhqSaRxwMT3ASFcaw
  distributions: sdist bdist_egg bdist_wheel
  skip_existing: true
